//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.22 at 09:53:36 PM EDT 
//

package org.blockworldshared.math.functions.loader;

import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.blockworld.math.functions.loader package.
 * <p>
 * An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups. Factory methods for each of these are
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema
     * derived classes for package: org.blockworld.math.functions.loader
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Functions.Function.FunctionComponent }
     * 
     */
    public Functions.Function.FunctionComponent createFunctionsFunctionFunctionComponent() {
        return new Functions.Function.FunctionComponent();
    }

    /**
     * Create an instance of {@link Functions.Function }
     * 
     */
    public Functions.Function createFunctionsFunction() {
        return new Functions.Function();
    }

    /**
     * Create an instance of {@link Functions.Function.StringComponent }
     * 
     */
    public Functions.Function.StringComponent createFunctionsFunctionStringComponent() {
        return new Functions.Function.StringComponent();
    }

    /**
     * Create an instance of {@link Functions.Function.FloatComponent }
     * 
     */
    public Functions.Function.FloatComponent createFunctionsFunctionFloatComponent() {
        return new Functions.Function.FloatComponent();
    }

    /**
     * Create an instance of {@link Functions }
     * 
     */
    public Functions createFunctions() {
        return new Functions();
    }

    /**
     * Create an instance of {@link Functions.Function.IntComponent }
     * 
     */
    public Functions.Function.IntComponent createFunctionsFunctionIntComponent() {
        return new Functions.Function.IntComponent();
    }

}
